name: Gradle Build and Docker Publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        distribution: "zulu"
        java-version: 19
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: gradle shadowJar
    - uses: actions/upload-artifact@v3
      with:
        name: scrambler.jar
        path: build/libs/scrambler.jar
  push:
    name: Push Docker image to GitHub Packages
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: scrambler.jar
      - name: Docker Build & Push Action
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: scrambler
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
          addLatest: true
