name: Gradle Build and Docker Publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        distribution: "zulu"
        java-version: 21
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle
    - name: Build with Gradle
      run: gradle build jar
    - uses: actions/upload-artifact@v4
      with:
        name: scrambler.jar
        path: build/libs/scrambler.jar
  push:
    name: Push Docker image to GitHub Packages
    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v5
        with:
          name: scrambler.jar
      - name: Docker Build & Push Action
        uses: docker/build-push-action@v6
        with:
          context: .
          tags: nogesma/scrambler:latest
          push: true
